title: "DeePMD + dpgen — But Make It Make Sense"
author: Krishna Patel
logo: ""

execute:
  execute_notebooks: "off"

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - substitution
    - tasklist

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  toc_depth: 3

repository:
  url: https://github.com/crisnapatel/deepmd-handbook
  branch: main

sphinx:
  extra_extensions:
    - sphinx_copybutton
  local_extensions:
  config:
    html_css_files:
      - custom.css
    copybutton_prompt_text: "$ "
    copybutton_only_copy_prompt_lines: true
    copybutton_remove_prompts: true
